// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtvOCgoob1MLYjIn_HY8ZjcRnFSUxkiM4',
    appId: '1:489275851127:web:16b5ae22da8b67d46b2172',
    messagingSenderId: '489275851127',
    projectId: 'click-n-collect-6d63f',
    authDomain: 'click-n-collect-6d63f.firebaseapp.com',
    storageBucket: 'click-n-collect-6d63f.appspot.com',
    measurementId: 'G-VD9398GE84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNVrR4M2Pw72tYntnex32xfipWcEUy9YY',
    appId: '1:489275851127:android:7907810142a58fab6b2172',
    messagingSenderId: '489275851127',
    projectId: 'click-n-collect-6d63f',
    storageBucket: 'click-n-collect-6d63f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjvSImFlYYBo228dEfoKyPgt2WfgamVkc',
    appId: '1:489275851127:ios:727856308761a70b6b2172',
    messagingSenderId: '489275851127',
    projectId: 'click-n-collect-6d63f',
    storageBucket: 'click-n-collect-6d63f.appspot.com',
    iosClientId: '489275851127-hogrg5sbdr1g3qiu5p7tjbgk3dl0svse.apps.googleusercontent.com',
    iosBundleId: 'com.example.clickNCollect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjvSImFlYYBo228dEfoKyPgt2WfgamVkc',
    appId: '1:489275851127:ios:2ea5f90576ebd57b6b2172',
    messagingSenderId: '489275851127',
    projectId: 'click-n-collect-6d63f',
    storageBucket: 'click-n-collect-6d63f.appspot.com',
    iosClientId: '489275851127-ntrc13kujcp70urj5qons81raubsev1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.clickNCollect.RunnerTests',
  );
}
